version: '3.8'
services:
  postgres:
    image: postgres:14.5-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_twitter
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"